# Site settings
title: Flatiron School
header-img: img/home-bg.png
email: superbiscuit@gmail.com
copyright_name: f3mshep
description: > # this means to ignore newlines until "baseurl:"
  Or: How I Learned to Stop Stressing and Love to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: Petrichor175
github_username:  f3mshep
learn_profile: f3mshep
email_username: superbiscuit@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
